### PR TITLE
Documentation Updates and Minor Bug Fixes

### PR DESCRIPTION
**Pull request by camicarballo**
Pyrameter updates makes hardware tests fail. 
Need to integrate pyrameter backend into shadho.

### CODE REVIEW

**Comment by jeffkinnison** [comment]
Hey, we should roll back 7879228--I changed Hardware to have an empty ModelGroup so that all instantiation is happening in __init__. Models will be dynamically added/removed as shadho runs (I'm working on Shadho.assign_to_ccs), and we can avoid some unnecessary error checking this way.

**Comment by camicarballo** [comment]
ModelGroup needs to be passed in a valid Model object in order to be instantiated, otherwise it throws an error. So that would need to be changed as well then.

**Comment by jeffkinnison** [comment]
Just pushed an update to pyrameter/modelgroup.py

**Comment by camicarballo** [comment]
Fixed.

**Pull request merged**
